# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"color:#fff;\n"
"font-size:20px;\n"
"")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 80, 351, 98))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_login = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_login.setObjectName("label_login")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_login.setStyleSheet("QLineEdit {\n"
"\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_login)
        self.label_password = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_password.setObjectName("label_password")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.label_header = QtWidgets.QLabel(Dialog)
        self.label_header.setGeometry(QtCore.QRect(30, 32, 351, 31))
        self.label_header.setStyleSheet("font-size:26px;")
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setGeometry(QtCore.QRect(30, 180, 351, 31))
        self.label_status.setStyleSheet("border:#00ff00 1px solid;")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.pushButton_authorization = QtWidgets.QPushButton(Dialog)
        self.pushButton_authorization.setGeometry(QtCore.QRect(30, 245, 161, 41))
        self.pushButton_authorization.setStyleSheet("QPushButton {\n"
"border:1px solid #fff;\n"
"border-radius:25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_authorization.setObjectName("pushButton_authorization")
        self.pushButton_registration = QtWidgets.QPushButton(Dialog)
        self.pushButton_registration.setGeometry(QtCore.QRect(230, 245, 151, 41))
        self.pushButton_registration.setStyleSheet("QPushButton {\n"
"border:1px solid #fff;\n"
"border-radius:25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_registration.setObjectName("pushButton_registration")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_login.setText(_translate("Dialog", "Логин"))
        self.label_password.setText(_translate("Dialog", "Пароль"))
        self.label_header.setText(_translate("Dialog", "Войти в систему"))
        self.label_status.setText(_translate("Dialog", "Введите логин и пароль"))
        self.pushButton_authorization.setText(_translate("Dialog", "Вход"))
        self.pushButton_registration.setText(_translate("Dialog", "Регистрация"))
