# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 667)
        MainWindow.setMinimumSize(QtCore.QSize(635, 667))
        MainWindow.setMaximumSize(QtCore.QSize(635, 667))
        MainWindow.setStyleSheet("background-color:#001424;\n"
"font-family:\'Oswald\',\'sans-serif\';")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_calculator = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculator.setGeometry(QtCore.QRect(110, 270, 421, 61))
        self.pushButton_calculator.setStyleSheet("QPushButton:hover {\n"
"        font-size:23px;\n"
"        border:3px solid #fff;\n"
"        font-weight:900;\n"
"    }\n"
"QPushButton{\n"
"       border:1px solid #fff;\n"
"       font-size:20px;\n"
"       color:#fff;\n"
"    }")
        self.pushButton_calculator.setObjectName("pushButton_calculator")
        self.pushButton_training = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_training.setGeometry(QtCore.QRect(110, 360, 421, 61))
        self.pushButton_training.setStyleSheet("border:1px solid #fff;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_training.setObjectName("pushButton_training")
        self.pushButton_nutrition = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nutrition.setGeometry(QtCore.QRect(110, 450, 421, 61))
        self.pushButton_nutrition.setStyleSheet("border:1px solid #fff;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_nutrition.setObjectName("pushButton_nutrition")
        self.pushButton_ru = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ru.setGeometry(QtCore.QRect(10, 10, 51, 23))
        self.pushButton_ru.setStyleSheet("border:1px solid #fff;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_ru.setObjectName("pushButton_ru")
        self.pushButton_en = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_en.setGeometry(QtCore.QRect(70, 10, 51, 23))
        self.pushButton_en.setStyleSheet("border:1px solid #fff;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_en.setObjectName("pushButton_en")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 0, 131, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/filename.png"))
        self.label.setObjectName("label")
        self.pushButton_sign = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sign.setGeometry(QtCore.QRect(550, 10, 71, 31))
        self.pushButton_sign.setStyleSheet("border:1px solid #fff;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_sign.setObjectName("pushButton_sign")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(410, 10, 131, 31))
        self.label_name.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_name.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_name.setStyleSheet("\n"
"font-size:20px;\n"
"color:#fff;")
        self.label_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 421, 101))
        self.label_2.setStyleSheet("font-size:127px;\n"
"color:#fff;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_info.setGeometry(QtCore.QRect(110, 540, 421, 61))
        self.pushButton_info.setStyleSheet("border:1px solid #fff;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_info.setObjectName("pushButton_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_calculator.setText(_translate("MainWindow", "Калькулятор"))
        self.pushButton_training.setText(_translate("MainWindow", "Тренировки"))
        self.pushButton_nutrition.setText(_translate("MainWindow", "Питание"))
        self.pushButton_ru.setText(_translate("MainWindow", "RU"))
        self.pushButton_en.setText(_translate("MainWindow", "EN"))
        self.pushButton_sign.setText(_translate("MainWindow", "Войти"))
        self.label_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:15pt;\">Гость</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "BeneFit"))
        self.pushButton_info.setText(_translate("MainWindow", "О приложении"))
