# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nutrition.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NutritionWindow(object):
    def setupUi(self, NutritionWindow):
        NutritionWindow.setObjectName("NutritionWindow")
        NutritionWindow.resize(927, 775)
        NutritionWindow.setStyleSheet("background-color:#001424;\n"
"color:#fff;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(NutritionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableView(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(30, 190, 681, 221))
        self.table.setStyleSheet("font-size:15px;\n"
"height:20px;\n"
"background-color:#001424;\n"
"color:#fff;\n"
"\n"
"")
        self.table.setObjectName("table")
        self.search_field = QtWidgets.QLineEdit(self.centralwidget)
        self.search_field.setGeometry(QtCore.QRect(30, 90, 871, 71))
        self.search_field.setStyleSheet("font-size:35px;\n"
"height: 60px;\n"
"border:1px solid #fff;\n"
"")
        self.search_field.setObjectName("search_field")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(730, 440, 171, 101))
        self.pushButton.setStyleSheet("border:1px solid #fff;\n"
"border-radius:25px;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 560, 171, 101))
        self.pushButton_2.setStyleSheet("border:1px solid #fff;\n"
"border-radius:25px;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(730, 190, 171, 71))
        self.pushButton_3.setStyleSheet("border:1px solid #fff;\n"
"border-radius:25px;\n"
"font-size:60px;\n"
"color:#fff;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 670, 331, 61))
        self.pushButton_4.setStyleSheet("border:1px solid #fff;\n"
"border-radius:25px;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 670, 311, 61))
        self.pushButton_5.setStyleSheet("border:1px solid #fff;\n"
"border-radius:25px;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.table2 = QtWidgets.QTableView(self.centralwidget)
        self.table2.setGeometry(QtCore.QRect(30, 440, 681, 221))
        self.table2.setStyleSheet("font-size:15px;height:20px;\n"
"")
        self.table2.setObjectName("table2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(270, 10, 421, 61))
        self.pushButton_6.setStyleSheet("border:1px solid #fff;\n"
"border-radius:25px;\n"
"font-size:20px;\n"
"color:#fff;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 20, 121, 41))
        self.pushButton_7.setStyleSheet("border:1px solid #fff;\n"
"border-radius:20px;\n"
"font-size:20px;\n"
"color:#fff;\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(750, 280, 131, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/frut.png"))
        self.label.setObjectName("label")
        NutritionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NutritionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 21))
        self.menubar.setObjectName("menubar")
        NutritionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NutritionWindow)
        self.statusbar.setObjectName("statusbar")
        NutritionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NutritionWindow)
        QtCore.QMetaObject.connectSlotsByName(NutritionWindow)

    def retranslateUi(self, NutritionWindow):
        _translate = QtCore.QCoreApplication.translate
        NutritionWindow.setWindowTitle(_translate("NutritionWindow", "MainWindow"))
        self.pushButton.setText(_translate("NutritionWindow", "Добавить"))
        self.pushButton_2.setText(_translate("NutritionWindow", "Очистить"))
        self.pushButton_3.setText(_translate("NutritionWindow", "+"))
        self.pushButton_4.setText(_translate("NutritionWindow", "Сохранить"))
        self.pushButton_5.setText(_translate("NutritionWindow", "Загрузить"))
        self.pushButton_6.setText(_translate("NutritionWindow", "Питание"))
        self.pushButton_7.setText(_translate("NutritionWindow", "Главная"))
